version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/src
    volumes:
      - .:/src
